

###
get http://localhost:5000/auth/get
###
post http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"2309000satyam@gmail.com",
    "name":"satyam",
    "password":"satyam"
}

###
post http://localhost:5000/auth/verifyemail
Content-Type: application/json

{
    "code":"137423"
}

###
post http://localhost:5000/auth/resend
Content-Type: application/json

{
    "email":"2309000satyam@gmail.com"
}